/**
 * Swagger POI
 * POI
 *
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 * Contact: henmerlin@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Position } from './position';


export interface Poi { 
    id?: number;
    name: string;
    radiusMeters: number;
    position: Position;
}
